server:
    port: 8080
    servlet:
        context-path: "/academy"

spring:
    application:
        name: studentapp
    datasource:
        url: jdbc:h2:mem:academydb
        username: sa
        password: password
        
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
        show_sql: true
        
    output:
        ansi:
            enabled: ALWAYS  
    h2:
        console.enabled: true
        console.settings.trace: false 
        spring.h2.console.settings.web-allow-others: false